<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    private const TABLES = ['platform_tenant_imports', 'platform_tenant_import_rows'];

    public function up(): void
    {
        foreach (self::TABLES as $table) {
            $next = (int) DB::table($table)->max('id') + 1;
            DB::statement("ALTER TABLE {$table} ALTER COLUMN id DROP DEFAULT");
            DB::statement("ALTER TABLE {$table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {$next})");
        }
    }

    public function down(): void
    {
        foreach (self::TABLES as $table) {
            DB::statement("ALTER TABLE {$table} ALTER COLUMN id DROP IDENTITY IF EXISTS");
            DB::statement("ALTER TABLE {$table} ALTER COLUMN id SET DEFAULT nextval('{$table}_id_seq'::regclass)");
            $max = (int) DB::table($table)->max('id');
            DB::select("SELECT setval('{$table}_id_seq', ?, ?)", [max(1, $max), $max > 0]);
        }
    }
};
