export const BLUEPOS_RIBBON_TAB_ICONS: Record<string, string> = {
  definition: '/icons/bluepos-v2/definition.svg',
  'daily-entries': '/icons/bluepos-v2/daily-entries.svg',
  reports: '/icons/bluepos-v2/reports.svg',
  tools: '/icons/bluepos-v2/tools.svg',
  administration: '/icons/bluepos-v2/administration.svg',
  help: '/icons/bluepos-v2/help.svg',
}

export const BLUEPOS_RIBBON_COMMAND_ICONS: Record<string, string> = {
  backup: '/icons/bluepos-v2/backup-restore.svg',
  settings: '/icons/bluepos-v2/business-settings.svg',
  products: '/icons/bluepos-v2/define-products.svg',
  tabular: '/icons/bluepos-v2/tabular-view.svg',
  'stock-taking': '/icons/bluepos-v2/stock-taking.svg',
  categories: '/icons/bluepos-v2/categories.svg',
  subcategories: '/icons/bluepos-v2/subcategories.svg',
  brands: '/icons/bluepos-v2/brands.svg',
  units: '/icons/bluepos-v2/units.svg',
  suppliers: '/icons/bluepos-v2/suppliers.svg',
  parties: '/icons/bluepos-v2/vendor-customer-accounts.svg',
  'opening-stock': '/icons/bluepos-v2/opening-stock.svg',
  barcodes: '/icons/bluepos-v2/barcode-printing.svg',
  'price-lists': '/icons/bluepos-v2/price-lists.svg',

  'sales-invoice': '/icons/bluepos-v2/sales-invoice.svg',
  'sales-return': '/icons/bluepos-v2/sales-return.svg',
  'purchase-invoice': '/icons/bluepos-v2/purchase-invoice.svg',
  'purchase-return': '/icons/bluepos-v2/purchase-return.svg',
  adjustments: '/icons/bluepos-v2/adjustments.svg',
  vouchers: '/icons/bluepos-v2/vouchers.svg',
  'product-view': '/icons/bluepos-v2/product-view.svg',
  ledger: '/icons/bluepos-v2/vendor-customer-ledger.svg',
  cash: '/icons/bluepos-v2/daily-cash-position.svg',

  'accounts-reports': '/icons/bluepos-v2/accounts-reports.svg',
  'daily-reports': '/icons/bluepos-v2/daily-reports.svg',
  'product-reports': '/icons/bluepos-v2/product-reports.svg',
  'advance-sales': '/icons/bluepos-v2/advance-sales-view.svg',
  'party-reports': '/icons/bluepos-v2/vendor-customer-reports.svg',

  roles: '/icons/bluepos-v2/manage-groups.svg',
  users: '/icons/bluepos-v2/configure-users.svg',
  devices: '/icons/bluepos-v2/devices.svg',
  'custom-query': '/icons/bluepos-v2/custom-query.svg',
  'report-headings': '/icons/bluepos-v2/report-headings.svg',
  options: '/icons/bluepos-v2/software-options.svg',
  'recalc-stock': '/icons/bluepos-v2/recalculate-stock.svg',
  calculator: '/icons/bluepos-v2/calculator.svg',
  lock: '/icons/bluepos-v2/lock-software.svg',

  branches: '/icons/bluepos-v2/branches.svg',
  warehouses: '/icons/bluepos-v2/warehouses.svg',
  security: '/icons/bluepos-v2/security.svg',
  plan: '/icons/bluepos-v2/plan.svg',
  about: '/icons/bluepos-v2/about.svg',
  docs: '/icons/bluepos-v2/documentation.svg',
}
